(function(root){
  'use strict';
  const DB='arsca_topps_offline_v1',VERSION=1;
  const result=request=>new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
  const complete=tx=>new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Topps import aborted'));});
  const normalize=value=>String(value||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
  const words=value=>[...new Set(normalize(value).split(/\s+/).filter(word=>word.length>1))];
  function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,VERSION);request.onupgradeneeded=()=>{const db=request.result,cards=db.createObjectStore('cards',{keyPath:['version','id']});cards.createIndex('tokens','tokenKeys',{multiEntry:true});cards.createIndex('set','setKey');cards.createIndex('number','numberKey');cards.createIndex('year','yearKey');db.createObjectStore('sets',{keyPath:['version','id']}).createIndex('version','version');db.createObjectStore('meta',{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
  async function getMeta(){const db=await openDb();return result(db.transaction('meta','readonly').objectStore('meta').get('active'));}
  async function remoteManifest(worker=root.WORKER||''){const response=await fetch(worker+'/catalog/topps/manifest',{cache:'no-store'}),data=await response.json().catch(()=>null);if(!response.ok||!data?.version)throw new Error(data?.error||`Topps manifest HTTP ${response.status}`);return data;}
  async function downloadEach(worker,type,onBatch){const response=await fetch(worker+`/catalog/topps/download?file=${type}`,{cache:'no-store'});if(!response.ok)throw new Error(`Topps ${type} download HTTP ${response.status}`);if(!response.body||typeof DecompressionStream==='undefined')throw new Error('Update Chrome to import compressed offline catalogs');const reader=response.body.pipeThrough(new DecompressionStream('gzip')).getReader(),decoder=new TextDecoder();let pending='',batch=[],count=0;while(true){const {value,done}=await reader.read();pending+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=pending.split('\n');pending=lines.pop()||'';for(const line of lines){if(!line)continue;batch.push(JSON.parse(line));count++;if(batch.length>=1000){await onBatch(batch);batch=[];}}if(done)break;}if(pending.trim()){batch.push(JSON.parse(pending));count++;}if(batch.length)await onBatch(batch);return count;}
  function prepare(row,version){const searchText=normalize(row.searchText||[row.year,row.brand,row.product,row.sport,row.setName,row.releaseName,row.cardNumber,row.player,row.subject,row.team,row.notes,row.section].join(' '));return{...row,version,searchText,tokenKeys:words(searchText).map(word=>version+'|'+word),setKey:version+'|'+String(row.setId||''),numberKey:version+'|'+normalize(row.cardNumber),yearKey:version+'|'+String(row.year||'')};}
  async function erase(db,version){if(!version)return;for(const name of ['cards','sets']){const tx=db.transaction(name,'readwrite');tx.objectStore(name).delete(IDBKeyRange.bound([version,''],[version,'\uffff']));await complete(tx);}}
  async function batches(db,name,rows,size=1000){for(let i=0;i<rows.length;i+=size){const tx=db.transaction(name,'readwrite'),store=tx.objectStore(name);rows.slice(i,i+size).forEach(row=>store.put(row));await complete(tx);await new Promise(resolve=>(root.requestAnimationFrame||setTimeout)(resolve));}}
  async function sync(options={}){const worker=options.worker||root.WORKER||'',manifest=await remoteManifest(worker),prior=await getMeta();if(prior?.version===manifest.version&&!options.force)return{updated:false,manifest,meta:prior};const db=await openDb(),version=String(manifest.version);await erase(db,version);try{const setCount=await downloadEach(worker,'sets',rows=>batches(db,'sets',rows.map(row=>({...row,version}))));const rowCount=await downloadEach(worker,'cards',rows=>batches(db,'cards',rows.map(row=>prepare(row,version))));const meta={id:'active',version,rowCount,setCount,generatedAt:manifest.generatedAt||'',lastImportedAt:new Date().toISOString(),manifest};const tx=db.transaction('meta','readwrite');tx.objectStore('meta').put(meta);await complete(tx);if(prior?.version&&prior.version!==version)await erase(db,prior.version);return{updated:true,manifest,meta};}catch(error){await erase(db,version);throw error;}}
  async function getSets(){const meta=await getMeta();if(!meta?.version)return[];const db=await openDb();return result(db.transaction('sets','readonly').objectStore('sets').index('version').getAll(meta.version));}
  async function indexed(index,key,max=2000){const db=await openDb();return result(db.transaction('cards','readonly').objectStore('cards').index(index).getAll(key,max));}
  function matches(card,filters){if(filters.setId&&card.setId!==filters.setId)return false;if(filters.year&&String(card.year)!==String(filters.year))return false;if(filters.sport&&normalize(card.sport)!==normalize(filters.sport))return false;if(filters.number&&normalize(card.cardNumber)!==normalize(filters.number))return false;if(filters.flag&&!card.flags?.[filters.flag])return false;return words(filters.q).every(word=>card.searchText.includes(word));}
  async function search(filters={},limit=20){const meta=await getMeta();if(!meta?.version)return[];const version=meta.version,wanted=words(filters.q);let rows;if(filters.number)rows=await indexed('number',version+'|'+normalize(filters.number));else if(filters.setId)rows=await indexed('set',version+'|'+filters.setId,3000);else if(wanted.length)rows=await indexed('tokens',version+'|'+wanted.sort((a,b)=>b.length-a.length)[0]);else if(filters.year)rows=await indexed('year',version+'|'+filters.year);else return[];return rows.filter(card=>matches(card,filters)).map(card=>({...card,offlineScore:words(filters.q).length*8+(filters.number?80:0)+(filters.setId?50:0)})).slice(0,limit);}
  async function cardById(id){const meta=await getMeta();if(!meta?.version)return null;const db=await openDb();return result(db.transaction('cards','readonly').objectStore('cards').get([meta.version,id]));}
  async function status(){const meta=await getMeta();return{installed:!!meta?.version,version:meta?.version||'',rowCount:Number(meta?.rowCount||0),setCount:Number(meta?.setCount||0),generatedAt:meta?.generatedAt||'',lastImportedAt:meta?.lastImportedAt||''};}
  async function clear(){const meta=await getMeta(),db=await openDb();if(meta?.version)await erase(db,meta.version);const tx=db.transaction('meta','readwrite');tx.objectStore('meta').delete('active');await complete(tx);}
  root.ArsCaToppsOffline={openDb,manifest:remoteManifest,sync,search,getSets,cardById,status,clear,normalize,DB_NAME:DB};
})(typeof window!=='undefined'?window:globalThis);
