import assert from 'node:assert/strict';
import fs from 'node:fs';
import { DOMParser } from 'linkedom';
import { parsePage, catalogURL, ORIGIN } from '../extensions/bcw-catalog/parser.mjs';
import { parseCSV, exportCSV, parseImportCSV } from '../extensions/bcw-catalog/csv.mjs';
import { freshState, enqueue, acceptPage, collectedProducts, runQueue, verifySession } from '../extensions/bcw-catalog/engine.mjs';
import { prepareDropship, supplierItemId, refreshDropship, importDropshipBatch } from '../scripts/dropship-import.mjs';

const fixture = fs.readFileSync(new URL('./fixtures/bcw/product.html',import.meta.url),'utf8');
const category = fs.readFileSync(new URL('./fixtures/bcw/category.html',import.meta.url),'utf8');
const productURL = ORIGIN + '/current-comic-book-bag-board';
const p = parsePage(fixture,productURL,DOMParser).product;
assert.equal(p.sku,'1-CUR-BAGBRD'); assert.equal(p.pack_quantity,50);
assert.equal(p.cost,10.58); assert.equal(p.msrp,18.99);
assert.equal(p.price_tiers[1].quantity,10); assert.equal(p.price_tiers[1].price,9.40);
assert.equal(p.image_urls.length,2); assert.match(p.image_url,/front/);
assert.equal(p.availability,'in_stock'); assert.equal(p.upc,'722626903458');
assert.doesNotMatch(p.description,/badScript|display:none/);
assert.equal(p.specifications['Case Weight'],'26.4 lbs');
const backorder = parsePage(fixture.replace('<div class="stock available"></div>','<div class="stock available">Backorder</div>'),productURL,DOMParser).product;
assert.equal(backorder.availability,'backorder','Backorder overrides schema InStock');
assert.equal(parsePage(fixture.replace('</body>','<select name="super_attribute[1]"></select></body>'),productURL,DOMParser).product.requires_options,true);
assert.equal(catalogURL('/checkout/cart/add/'),''); assert.equal(catalogURL('https://evil.example/item'),'');
assert.equal(catalogURL('/comic-book-storage?p=2&color=red'),ORIGIN+'/comic-book-storage?p=2');
const parsedCategory = parsePage(category,ORIGIN+'/comic-book-storage',DOMParser);
assert.equal(parsedCategory.productLinks.length,2); assert.equal(parsedCategory.next.length,1);
const state=freshState(); state.queue=[];
enqueue(state,{url:productURL,kind:'product',category:'Comics > Bags'});
enqueue(state,{url:productURL,kind:'product',category:'Supplies > Premades'});
assert.equal(state.queue.length,1);
acceptPage(state,state.queue[0],{product:p});
enqueue(state,{url:productURL,kind:'product',category:'Other category'});
assert.equal(state.queue.length,0); assert.equal(collectedProducts(state)[0].category_paths.length,3);
const csv=exportCSV([{...p,name:'=HYPERLINK("evil")',description:'Line 1, "quoted"\nLine 2'}],'msrp');
assert.match(csv,/'=HYPERLINK/);
const roundtrip=parseImportCSV(csv)[0]; assert.equal(roundtrip.name,'=HYPERLINK("evil")'); assert.equal(roundtrip.price,18.99);
assert.equal(roundtrip.description,'Line 1, "quoted"\nLine 2'); assert.equal(roundtrip.image_urls.length,2);
assert.equal(parseImportCSV(exportCSV([p]))[0].valid,true,'Blank-price supplier rows can be drafts');
assert.equal(parseImportCSV('Name,Price,Image URL,Description\nTest,-5,,')[0].valid,false);
assert.equal(parseImportCSV('Test,3.50,https://example.com/a.jpg,"a,b"')[0].price,3.5);
assert.equal(parseImportCSV(exportCSV([p,p],'msrp'))[1].valid,false);
assert.throws(()=>parseCSV('name,"unclosed'),/unclosed/);

const options={storeId:'store-a',vendor:'BCW',category:'Supplies',publish:false,nowIso:'2026-09-16T12:00:00Z'};
const incoming=await prepareDropship({...p,price:18.99},options);
const draft=await prepareDropship({...p,price:null}, {...options,publish:true});
assert.equal(draft.data.onlineListed,false); assert.equal(draft.data.priceOverride,0);
assert.equal(incoming.data.supplierSku,p.sku); assert.equal(incoming.data.cost,undefined);
assert.notEqual(await supplierItemId('store-b','BCW',p.sku),incoming.id);
const old={...incoming,updated_at:'2026-09-16T11:00:00Z',data:{...incoming.data,name:'My custom title',priceOverride:24,onlineListed:true,description:'My description'}};
const unavailable=await prepareDropship({...p,price:99,availability:'out_of_stock'},options);
const refreshed=refreshDropship(old,unavailable);
assert.equal(refreshed.name,'My custom title'); assert.equal(refreshed.priceOverride,24); assert.equal(refreshed.quantity,0); assert.equal(refreshed.onlineListed,true);
assert.throws(()=>refreshDropship({...old,store_id:'other'},unavailable),/identity/);
assert.throws(()=>refreshDropship({...old,data:{...old.data,supplierCheckedAt:'2099-01-01'}},incoming),/Older/);
const dbRows=new Map();
const db=async (path,opt={})=>{
  if (!opt.method) return {data:[...dbRows.values()]};
  if (opt.method==='POST') {const created=[];for(const row of JSON.parse(opt.body)) if(!dbRows.has(row.id)){dbRows.set(row.id,{...row,updated_at:options.nowIso});created.push(row);}return {data:created};}
  const id=path.match(/[?&]id=eq\.([^&]+)/)[1]; assert.match(path,/store_id=eq.store-a/);
  const row={...dbRows.get(id),...JSON.parse(opt.body)};dbRows.set(id,row);return {data:[row]};
};
assert.equal((await importDropshipBatch([{...p,price:18.99}],options,db)).created,1);
assert.equal((await importDropshipBatch([{...p,price:30}],options,db)).updated,1);
assert.equal(dbRows.size,1);assert.equal([...dbRows.values()][0].data.priceOverride,18.99);
const casDb=async (path,opt={}) => opt.method==='PATCH'?{data:[]}:{data:[old]};
assert.equal((await importDropshipBatch([{...p,price:18.99}],options,casDb)).failed.length,1);

const response=(body,status=200)=>({ok:status===200,status,url:productURL,headers:new Headers(),text:async()=>body});
await assert.rejects(()=>verifySession(async()=>response('<form id="login-form"></form>')),/Sign in/);
await verifySession(async()=>response('<body class="customer-account-index"></body>'));
let calls=0, saved=0; const run=freshState(); run.queue=[{url:productURL,kind:'product'}];
await runQueue(run,{save:async()=>saved++,notify:()=>{},shouldStop:()=>false,verify:async()=>{},delay:async()=>{},fetcher:async()=>{calls++;return response(fixture);},parser:(html,url)=>parsePage(html,url,DOMParser)});
assert.equal(calls,1);assert.equal(run.queue.length,0);assert.ok(saved);assert.ok(run.finished_at);
const retry=freshState(); retry.queue=[{url:productURL,kind:'product'}];calls=0;
await runQueue(retry,{save:async()=>{},notify:()=>{},shouldStop:()=>false,verify:async()=>{},delay:async()=>{},fetcher:async()=>{calls++;return response('',500);}});
assert.equal(calls,3);assert.equal(retry.failures.length,1);
const throttled=freshState();
await assert.rejects(()=>runQueue(throttled,{save:async()=>{},notify:()=>{},shouldStop:()=>false,verify:async()=>{},delay:async()=>{},fetcher:async()=>response('',429)}),/429/);
assert.equal(throttled.queue.length,1,'Throttling preserves the pending page');
console.log('BCW parser, CSV, queue, authentication, retries, draft import, SKU deduplication, and refresh tests passed.');
