const assert=require('node:assert/strict');
const fs=require('node:fs');
const hub=require('../scripts/comic-issue-hub');
const tmnt=hub.parseComicQuery('IDW TMNT #1 foil');
assert.equal(tmnt.raw,'IDW TMNT #1 foil');
assert.equal(tmnt.seriesGuess,'Teenage Mutant Ninja Turtles');
assert.equal(tmnt.issueNumber,'1');
assert.equal(tmnt.publisherGuess,'IDW');
assert.ok(tmnt.variantTerms.includes('foil'));
const unknown=hub.parseComicQuery('Something Is Killing The Children 1');
assert.equal(unknown.seriesGuess,'Something Is Killing The Children');
assert.equal(unknown.issueNumber,'1');
const queries=hub.buildSweepQueries({seriesTitle:'Teenage Mutant Ninja Turtles',publisher:'IDW',currentIssueNumber:'2',yearGuess:'2020'});
assert.ok(queries.every(q=>/IDW|2020/i.test(q)),'run navigation queries must retain run/year context');
assert.equal(hub.adjacentIssue('0',-1),0);
assert.equal(hub.adjacentIssue('1',1),2);
assert.equal(hub.adjacentIssue('1A',1),null);
const groups=hub.groupCandidates([{productId:'a',productName:'Teenage Mutant Ninja Turtles #1 IDW Cover A',consoleName:'Comics',imageUrl:'https://x/a.jpg',comicPrices:{ungraded:10,grade9_8:80}},{productId:'b',productName:'Teenage Mutant Ninja Turtles #1 Mirage Second Print',consoleName:'Comics',comicPrices:{ungraded:20,grade9_8:100}}],hub.parseComicQuery('TMNT 1'));
assert.equal(groups.length,2);
assert.ok(groups.some(g=>g.publisher==='IDW'));
const dated=hub.groupCandidates([{productId:'new',productName:'TMNT #1 IDW',releaseDate:'2011-01-01'},{productId:'old',productName:'TMNT #1 Mirage',releaseDate:'1984-01-01'}],hub.parseComicQuery('TMNT 1'));
assert.equal(dated[0].yearGuess,'1984','run groups should sort oldest to newest');
const dashboard=fs.readFileSync(require('node:path').join(__dirname,'..','dashboard.html'),'utf8');
const worker=fs.readFileSync(require('node:path').join(__dirname,'..','cloudflare-worker-full.js'),'utf8');
assert.match(worker,/comic-sweep/);
assert.match(worker,/pcFetch\('\/api\/products'/);
assert.doesNotMatch(dashboard,/cacheComicExternalCover|cachedCoverBlobKey|comicsDb(?:Put|Get)\('images'/);
assert.match(dashboard,/createObjectStore\('userPhotos'/);
assert.match(dashboard,/Raw \/ Ungraded/);
assert.match(worker,/METRON_USER/);
assert.match(worker,/METRON_PASS/);
assert.match(worker,/\/comic\/metron\/search/);
assert.match(worker,/\/comic\\\/metron\\\/issue/);
assert.match(worker,/series_name/);
assert.match(worker,/metron:\s*!!\(env\.METRON_USER && env\.METRON_PASS\)/);
assert.match(dashboard,/function searchMetronComicCatalog/);
assert.match(dashboard,/function hydrateMetronComicResult/);
assert.match(dashboard,/function confirmMetronComicCover/);
assert.match(dashboard,/function selectMetronComicCover/);
assert.match(dashboard,/function openComicDetailsAndHydrate/);
assert.match(dashboard,/COMIC INFO, COVERS \+ EXACT PRICES/);
assert.match(dashboard,/SELECT THE EXACT COVER/);
assert.match(dashboard,/Cover artist/);
assert.match(dashboard,/availableCovers:r\.metronCovers/);
assert.match(dashboard,/function inventoryComicInfoHtml/);
assert.match(dashboard,/KEY ISSUE STATUS NEEDS A VERIFIED SOURCE/);
assert.match(dashboard,/comic_cover_/);
assert.doesNotMatch(dashboard,/id="qpl-comic-issue"/,'comic research should use one search box');
assert.doesNotMatch(dashboard,/function searchComicsOfflineCache|function saveComicsCacheResults/,'comic catalog searches must not use device cache');
assert.match(dashboard,/No device comic catalog is searched/);
assert.match(dashboard,/if\(qplCategoryKey\(document\.getElementById\('qpl-cat'\)/,'comic typing should not auto-fire provider calls');
assert.match(dashboard,/BOOK INFO · METRON/);
assert.match(dashboard,/METRON RECORD/);
assert.match(dashboard,/GCD RECORD/);
assert.match(dashboard,/PRICECHARTING/);
assert.match(worker,/source:'Metron'.*priceCandidates:\[\]/s,'initial comic search should not wait for PriceCharting');
assert.match(worker,/comic-pricecharting:/,'selected comic PriceCharting candidates should be server cached');
assert.match(worker,/matchingComicPcCandidates/,'comic PriceCharting matches must reject non-comic categories');
assert.match(worker,/\^comic books\\b/,'comic matching must require a real PriceCharting Comic Books catalog');
assert.match(worker,/normalized\.startsWith\(seriesPhrase/,'comic variants must remain inside the selected series');
assert.match(worker,/console:'Comics'/,'comic PriceCharting lookup must request the comics catalog');
assert.match(worker,/pricechartingProductId/,'PriceCharting cover variants must be returned as selectable covers');
assert.match(dashboard,/cover\.pricechartingProductId/,'selecting a PriceCharting cover must load its exact prices');
assert.match(worker,/series\/\$\{issue\.seriesId\}\/issue_list/,'selected issue should load its series cover list');
assert.match(worker,/priceMatch/,'selected issue should return a hydrated exact PriceCharting product');
assert.match(worker,/pcFetch\('\/api\/product'/,'comic pricing must hydrate the search candidate with product detail prices');
assert.match(worker,/writers:creditNames/);
assert.match(worker,/coverArtists:creditNames/);
const searchStart=dashboard.indexOf('async function searchQuickCatalog');
const comicRoute=dashboard.indexOf("recordSearchPlanRoute(searchPlan,'/comic/metron/search'",searchStart);
const localRoute=dashboard.indexOf('smartSearchLocalItems(q, all, 15)',searchStart);
assert.ok(comicRoute>searchStart&&comicRoute<localRoute,'comic search must return through Metron before shared inventory/provider fan-out');
console.log('comic issue hub tests passed');
