const assert=require('node:assert/strict');
const fs=require('node:fs');
const hub=require('../scripts/comic-issue-hub');
const tmnt=hub.parseComicQuery('IDW TMNT #1 foil');
assert.equal(tmnt.raw,'IDW TMNT #1 foil');
assert.equal(tmnt.seriesGuess,'Teenage Mutant Ninja Turtles');
assert.equal(tmnt.issueNumber,'1');
assert.equal(tmnt.publisherGuess,'IDW');
assert.ok(tmnt.variantTerms.includes('foil'));
const unknown=hub.parseComicQuery('Something Is Killing The Children 1');
assert.equal(unknown.seriesGuess,'Something Is Killing The Children');
assert.equal(unknown.issueNumber,'1');
const creator=hub.parseComicQuery('cover artist: Jim Lee');
assert.equal(creator.creatorGuess,'Jim Lee');
assert.equal(creator.seriesGuess,'');
const preferred=hub.pickSeriesPreference({tmnt:{seriesId:'42',seriesName:'Teenage Mutant Ninja Turtles',aliases:['tmnt'],lastUsedAt:'2026-07-22T12:00:00Z'}},hub.parseComicQuery('TMNT #7'));
assert.equal(preferred.seriesId,'42');
const queries=hub.buildSweepQueries({seriesTitle:'Teenage Mutant Ninja Turtles',publisher:'IDW',currentIssueNumber:'2',yearGuess:'2020'});
assert.ok(queries.every(q=>/IDW|2020/i.test(q)),'run navigation queries must retain run/year context');
assert.ok(queries.some(q=>/foil/i.test(q)),'the normal cover search must include foil products');
assert.ok(hub.variantLabels('Teenage Mutant Ninja Turtles #2 Cover D Metallic Foil Variant').includes('cover D'));
assert.ok(hub.variantLabels('Teenage Mutant Ninja Turtles #2 Cover D Metallic Foil Variant').includes('foil'));
assert.equal(hub.adjacentIssue('0',-1),0);
assert.equal(hub.adjacentIssue('1',1),2);
assert.equal(hub.adjacentIssue('1A',1),null);
const groups=hub.groupCandidates([{productId:'a',productName:'Teenage Mutant Ninja Turtles #1 IDW Cover A',consoleName:'Comics',imageUrl:'https://x/a.jpg',comicPrices:{ungraded:10,grade9_8:80}},{productId:'b',productName:'Teenage Mutant Ninja Turtles #1 Mirage Second Print',consoleName:'Comics',comicPrices:{ungraded:20,grade9_8:100}}],hub.parseComicQuery('TMNT 1'));
assert.equal(groups.length,2);
assert.ok(groups.some(g=>g.publisher==='IDW'));
const dated=hub.groupCandidates([{productId:'new',productName:'TMNT #1 IDW',releaseDate:'2011-01-01'},{productId:'old',productName:'TMNT #1 Mirage',releaseDate:'1984-01-01'}],hub.parseComicQuery('TMNT 1'));
assert.equal(dated[0].yearGuess,'1984','run groups should sort oldest to newest');
const dashboard=fs.readFileSync(require('node:path').join(__dirname,'..','dashboard.html'),'utf8');
const worker=fs.readFileSync(require('node:path').join(__dirname,'..','cloudflare-worker-full.js'),'utf8');
assert.match(worker,/comic-sweep/);
assert.match(worker,/pcFetch\('\/api\/products'/);
assert.doesNotMatch(dashboard,/cacheComicExternalCover|cachedCoverBlobKey|comicsDb(?:Put|Get)\('images'/);
assert.match(dashboard,/createObjectStore\('userPhotos'/);
assert.match(dashboard,/Raw \/ Ungraded/);
assert.match(worker,/METRON_USER/);
assert.match(worker,/METRON_PASS/);
assert.match(worker,/\/comic\/metron\/search/);
assert.match(worker,/\/comic\\\/metron\\\/issue/);
assert.match(worker,/series_id/);
assert.match(worker,/normalizeMetronSeries/);
assert.match(worker,/name:metronName\(series\.series \|\| series\)/,'Metron series list titles come from the official `series` field');
assert.match(worker,/imageUrl:''[\s\S]*modified:series\.modified/,'series choices must not claim an unrelated issue cover');
assert.match(worker,/creator_id/);
assert.match(worker,/metron:\s*!!\(env\.METRON_USER && env\.METRON_PASS\)/);
assert.match(dashboard,/function searchMetronComicCatalog/);
assert.match(dashboard,/function hydrateMetronComicResult/);
assert.match(dashboard,/function confirmMetronComicCover/);
assert.match(dashboard,/function selectMetronComicCover/);
assert.match(dashboard,/function openComicDetailsAndHydrate/);
assert.match(dashboard,/CHOOSE COVER \/ VARIANT \+ SEE PRICES/);
assert.match(dashboard,/SELECT THE EXACT COVER/);
assert.match(dashboard,/comic-cover-picker-grid/,'comic covers should use the larger cover-first picker');
assert.match(dashboard,/BOOK DETAILS, STORY & CREATORS/,'dense comic metadata should remain available in a collapsible section');
assert.match(dashboard,/Cover artist/);
assert.match(dashboard,/availableCovers:r\.metronCovers/);
assert.match(dashboard,/function inventoryComicInfoHtml/);
assert.match(dashboard,/function inventoryComicSearchFields/,'saved comic metadata must be searchable from inventory');
assert.match(dashboard,/function inventoryComicPeopleLine/,'comic creators must be visible in inventory');
assert.match(dashboard,/function metronSeriesToQplRow/,'comic title search must show Metron series and run choices');
assert.match(dashboard,/function chooseMetronComicSeries/,'choosing a Metron run must load that exact series id');
assert.match(dashboard,/function loadMetronComicSeriesPage/,'selected Metron runs must support server-backed issue pagination');
assert.match(dashboard,/series_id:String\(state\.series\.id\),page:String\(page\)/,'every issue page must retain the exact selected series id');
assert.match(dashboard,/ISSUES \$\{start\}-\$\{end\} OF \$\{total\}/,'comic pagination must show the visible issue range and total');
assert.match(dashboard,/NEXT 20/,'long comic runs need an explicit next-page control');
assert.match(worker,/url\.searchParams\.get\('page'\)/,'the Worker must accept a requested Metron issue page');
assert.match(worker,/pagination, priceCandidates/,'the Worker must return issue pagination metadata');
assert.doesNotMatch(worker,/const issues = rawIssues\.slice\(0, 20\)/,'the Worker must not truncate an upstream Metron page');
assert.match(dashboard,/comic_series_preferences_v1/,'recent comic runs must persist across devices');
const metronSearch=dashboard.slice(dashboard.indexOf('async function searchMetronComicCatalog'),dashboard.indexOf('async function hydrateMetronComicResult'));
assert.doesNotMatch(metronSearch,/params\.set\('series_id'/,'a remembered run must never silently lock a new title search');
assert.match(dashboard,/RECENT PICK - YOU CAN CHANGE IT/,'the prior run should be a visible suggestion only');
assert.match(dashboard,/function lazyLoadMetronSeriesPreviews/,'series cards should load an exact Metron first-issue preview');
assert.match(worker,/metronSeriesPreviewMatch/,'series previews must use a dedicated exact-series route');
assert.match(worker,/metronSeriesPreviewMatch\[1\][\s\S]*issue_list/,'series previews must come from the selected Metron series id');
assert.match(dashboard,/SELECT THIS RUN/,'every series choice needs an unmistakable selection action');
assert.match(dashboard,/comic_price_link_/,'exact comic price links must persist across devices');
assert.match(dashboard,/function selectComicPriceCandidate/,'ambiguous prices must be user-selectable');
assert.match(dashboard,/\.\.\.inventoryComicSearchFields\(item\)/,'inventory smart search must include comic creators and metadata');
assert.match(dashboard,/KEY ISSUE STATUS NEEDS A VERIFIED SOURCE/);
assert.match(dashboard,/comic_cover_/);
assert.doesNotMatch(dashboard,/id="qpl-comic-issue"/,'comic research should use one search box');
assert.doesNotMatch(dashboard,/function searchComicsOfflineCache|function saveComicsCacheResults/,'comic catalog searches must not use device cache');
assert.match(dashboard,/No device comic catalog is searched/);
assert.match(dashboard,/if\(qplCategoryKey\(document\.getElementById\('qpl-cat'\)/,'comic typing should not auto-fire provider calls');
assert.match(dashboard,/BOOK INFO · METRON/);
assert.match(dashboard,/METRON RECORD/);
assert.match(dashboard,/GCD RECORD/);
assert.match(dashboard,/PRICECHARTING/);
assert.match(worker,/source:'Metron'.*priceCandidates:\[\]/s,'initial comic search should not wait for PriceCharting');
assert.match(worker,/comic-pricecharting:/,'selected comic PriceCharting candidates should be server cached');
assert.match(worker,/matchingComicPcCandidates/,'comic PriceCharting matches must reject non-comic categories');
assert.match(worker,/\^comic books\\b/,'comic matching must require a real PriceCharting Comic Books catalog');
assert.match(worker,/identity\.series === seriesPhrase/,'comic prices must match the exact series title before the issue marker');
assert.match(worker,/identity\.number === number/,'comic prices must match the exact issue number');
assert.match(worker,/new RegExp\(`\^\$\{number\}\[a-z\]\$`/,'cover-letter products such as #1A and #1B must remain attached to base issue #1');
assert.match(worker,/const beforeIssue = issueMatch \? productName\.slice\(0, issueMatch\.index\)/,'PriceCharting identity must split the title before the issue marker');
assert.match(worker,/const descriptorMatch = beforeIssue\.match/,'bracketed PriceCharting cover names before the issue number must be captured as variants');
assert.match(worker,/\[identity\.descriptor, letteredCover, suffix\]/,'cover descriptors before and after the issue number must be retained');
assert.match(worker,/allowedYears\.has\(identity\.explicitYear\)/,'comic prices must reject incompatible run or publication years');
assert.doesNotMatch(worker,/pcFetch\('\/api\/products', \{ q, console:'Comics' \}\)/,'PriceCharting products only documents q; comic results must be filtered after retrieval');
assert.match(worker,/pricechartingProductId/,'PriceCharting cover variants must be returned as selectable covers');
assert.match(dashboard,/cover\.pricechartingProductId/,'selecting a PriceCharting cover must load its exact prices');
assert.match(dashboard,/VERIFY EXACT PRICECHARTING/,'the selected PriceCharting product must expose a direct verification link');
assert.match(dashboard,/SELECTED COVER/,'cover selection must be visible in the top-level comic result');
assert.match(worker,/function metronExactIssueRecords/,'selected issue should request exact Metron issue records');
assert.match(worker,/series_id:seriesId, number, page:1/,'cover lookup must retain the selected series and issue number');
assert.match(worker,/Math\.min\(3/,'Metron cover pagination must remain bounded');
assert.match(worker,/comic-pricecharting:v8/,'cover candidate cache must be invalidated after bracketed variant discovery');
assert.match(worker,/exact && `\$\{exact\} foil`/,'exact PriceCharting hydration must search foil editions');
assert.match(worker,/for \(const query of queries\)/,'PriceCharting cover searches must be sequential so provider throttling is respected');
assert.doesNotMatch(worker,/linkedPrice \? Promise\.resolve\(\[\]\) : comicPcCandidates/,'a saved exact price must not suppress discovery of other covers');
assert.match(worker,/standardPcCover[\s\S]*Metron \+ PriceCharting/,'the standard PriceCharting result must merge into the Metron main cover instead of duplicating it');
assert.match(dashboard,/candidateNumber===number[\s\S]*number\+'\[a-z\]\$'/,'the browser must retain PriceCharting cover-letter variants for a base issue');
assert.match(worker,/priceMatch/,'selected issue should return a hydrated exact PriceCharting product');
assert.match(worker,/pcFetch\('\/api\/product'/,'comic pricing must hydrate the search candidate with product detail prices');
assert.match(worker,/writers:creditNames/);
assert.match(worker,/coverArtists:creditNames/);
const searchStart=dashboard.indexOf('async function searchQuickCatalog');
const comicRoute=dashboard.indexOf("recordSearchPlanRoute(searchPlan,'/comic/metron/search'",searchStart);
const localRoute=dashboard.indexOf('smartSearchLocalItems(q, all, 15)',searchStart);
assert.ok(comicRoute>searchStart&&comicRoute<localRoute,'comic search must return through Metron before shared inventory/provider fan-out');
console.log('comic issue hub tests passed');
