const assert=require('node:assert/strict');
const fs=require('node:fs');
const hub=require('../scripts/comic-issue-hub');
const tmnt=hub.parseComicQuery('IDW TMNT #1 foil');
assert.equal(tmnt.raw,'IDW TMNT #1 foil');
assert.equal(tmnt.seriesGuess,'Teenage Mutant Ninja Turtles');
assert.equal(tmnt.issueNumber,'1');
assert.equal(tmnt.publisherGuess,'IDW');
assert.ok(tmnt.variantTerms.includes('foil'));
const unknown=hub.parseComicQuery('Something Is Killing The Children 1');
assert.equal(unknown.seriesGuess,'Something Is Killing The Children');
assert.equal(unknown.issueNumber,'1');
const queries=hub.buildSweepQueries({seriesTitle:'Teenage Mutant Ninja Turtles',publisher:'IDW',currentIssueNumber:'2',yearGuess:'2020'});
assert.ok(queries.every(q=>/IDW|2020/i.test(q)),'run navigation queries must retain run/year context');
assert.equal(hub.adjacentIssue('0',-1),0);
assert.equal(hub.adjacentIssue('1',1),2);
assert.equal(hub.adjacentIssue('1A',1),null);
const groups=hub.groupCandidates([{productId:'a',productName:'Teenage Mutant Ninja Turtles #1 IDW Cover A',consoleName:'Comics',imageUrl:'https://x/a.jpg',comicPrices:{ungraded:10,grade9_8:80}},{productId:'b',productName:'Teenage Mutant Ninja Turtles #1 Mirage Second Print',consoleName:'Comics',comicPrices:{ungraded:20,grade9_8:100}}],hub.parseComicQuery('TMNT 1'));
assert.equal(groups.length,2);
assert.ok(groups.some(g=>g.publisher==='IDW'));
const dashboard=fs.readFileSync(require('node:path').join(__dirname,'..','dashboard.html'),'utf8');
const worker=fs.readFileSync(require('node:path').join(__dirname,'..','cloudflare-worker-full.js'),'utf8');
assert.match(worker,/comic-sweep/);
assert.match(worker,/pcFetch\('\/api\/products'/);
assert.doesNotMatch(dashboard,/cacheComicExternalCover|cachedCoverBlobKey|comicsDb(?:Put|Get)\('images'/);
assert.match(dashboard,/createObjectStore\('userPhotos'/);
assert.match(dashboard,/Raw \/ Ungraded/);
console.log('comic issue hub tests passed');
