const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const dashboard=fs.readFileSync(path.join(__dirname,'..','dashboard.html'),'utf8');
assert.match(dashboard,/if\(name === 'inventory'\).*filterTable\(\).*setInvView\(_invView\)/s);
assert.match(dashboard,/Delete Test \/ Accident/);
assert.match(dashboard,/Type DELETE/);
assert.match(dashboard,/function inventoryDeleteBlockReason/);
assert.match(dashboard,/item\.soldAt \|\| item\.saleId \|\| item\.status === 'sold'/);
assert.match(dashboard,/buySessionId is source provenance, not proof of a completed payout/);
assert.match(dashboard,/!deleteBlockReason\?`<button class="hbtn danger"/, 'archived accidental entries can expose permanent delete');
assert.match(dashboard,/function editConsignorPerson/);
assert.match(dashboard,/function deleteConsignorPerson/);
assert.match(dashboard,/id="tab-browse"/);
assert.match(dashboard,/function renderCustomerInventoryBrowser/);
assert.match(dashboard,/Cost and private store data are hidden/);
assert.match(dashboard,/mutedTextColor:'rgba\(228,228,232,.68\)'/);
assert.match(dashboard,/Cost basis stays unchanged/);
const priceSyncApply = dashboard.match(/async function applySelectedPriceSyncUpdates\(\)[\s\S]*?function updatePriceAlertBanner/)?.[0] || '';
assert.ok(priceSyncApply, 'price sync apply function exists');
assert.doesNotMatch(priceSyncApply, /\bcost\s*:/, 'price sync must not update cost basis');
console.log('Inventory usability contract checks passed');
