import fs from 'node:fs';
import assert from 'node:assert/strict';

const html = fs.readFileSync('dashboard.html', 'utf8');

// Live bug: a real print went out with a completely blank back face (no QR,
// no barcode, just empty space where the code should be). Root cause: the
// wrap layout's back face always uses QR, generated by the separate local
// qrcode-generator.js -- but the pre-print guard only ever checked
// JsBarcode was loaded, never qrcode. generateLabelCodeCanvas() has no
// throw path of its own (QR fails -> falls back to barcode -> barcode fails
// -> silently returns an untouched blank canvas), so a missing qrcode
// library produced zero error, just an invisible code nobody noticed until
// the label was already printed.

const guardCount = (html.match(/if\(typeof JsBarcode === 'undefined' \|\| typeof qrcode === 'undefined'\) return alert\('Barcode library still loading -- try again in a moment'\);/g) || []).length;
assert.equal(guardCount, 2, 'both printInventoryLabels and downloadInventoryLabelPngs must guard on qrcode as well as JsBarcode, or either can silently print blank-coded labels');

assert.doesNotMatch(html, /if\(typeof JsBarcode === 'undefined'\) return alert\('Barcode library still loading/,
  'no call site may still check only JsBarcode -- the wrap layout always needs qrcode too');

console.log('Label code library guard contract checks passed');

// ── generateLabelCodeCanvas must leave a breadcrumb any time it falls back
// or fully fails, so a blank code is at least debuggable via console next
// time instead of a silent mystery ──
{
  const fnStart = html.indexOf('async function generateLabelCodeCanvas(value, style, size = 220){');
  const fnEnd = html.indexOf('\n}', fnStart) + 2;
  const fn = html.slice(fnStart, fnEnd);
  assert.match(fn, /console\.error\('generateLabelCodeCanvas: QR generation failed, falling back to barcode', e\);/, 'a QR-generation exception must be logged, not silently swallowed');
  assert.match(fn, /console\.error\('generateLabelCodeCanvas: qrcode-generator\.js is not loaded/, 'a missing qrcode library must be logged when a QR was actually requested');
  assert.match(fn, /console\.error\('generateLabelCodeCanvas: barcode generation also failed -- this label is printing with a blank code', e\);/, 'total failure (both QR and barcode) must be logged, since the caller has no other way to know the label is blank');
}

console.log('generateLabelCodeCanvas failure-logging contract checks passed');
