import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import zlib from 'node:zlib';
import { spawnSync } from 'node:child_process';

const root=path.resolve(import.meta.dirname,'..');
const worker=fs.readFileSync(path.join(root,'cloudflare-worker-full.js'),'utf8');
const browser=fs.readFileSync(path.join(root,'scripts/pricecharting/offline-browser.js'),'utf8');
const dashboard=fs.readFileSync(path.join(root,'dashboard.html'),'utf8');
const builder=fs.readFileSync(path.join(root,'scripts/pricecharting/build-offline-bundle.mjs'),'utf8');
assert.match(worker,/PRICECHARTING_OFFLINE_CATEGORIES[\s\S]*'video_games'[\s\S]*'yugioh'[\s\S]*'one_piece'/);
for(const excluded of ['sports','comics','funko','lego','coins','lorcana','digimon','gaming_magazines']) assert.doesNotMatch(worker,new RegExp(`PRICECHARTING_OFFLINE_CATEGORIES[^;]*'${excluded}'`));
assert.doesNotMatch(worker,/PRICECHARTING_OFFLINE_CATEGORIES[^;]*'pokemon'/);
assert.doesNotMatch(worker,/PRICECHARTING_OFFLINE_CATEGORIES[^;]*'mtg'/);
assert.match(browser,/one_piece/);
assert.match(browser,/identifiers/);
assert.match(browser,/search_tokens/);
assert.match(browser,/searchIndexReady/);
assert.match(browser,/categoryVersionUpc/);
assert.match(dashboard,/Pokémon is intentionally excluded here/);
assert.match(dashboard,/priceChartingOfflineCategoryFor/);
assert.match(builder,/PRICECHARTING_DOWNLOAD_DELAY_MS/);
assert.match(builder,/lastRemoteDownloadAt/);

const out=fs.mkdtempSync(path.join(os.tmpdir(),'arsca-pc-offline-'));
const result=spawnSync(process.execPath,['scripts/pricecharting/build-offline-bundle.mjs','--pricecharting=tests/fixtures/pricecharting/offline-sample.csv','--version=test','--out='+out],{cwd:root,encoding:'utf8'});
assert.equal(result.status,0,result.stderr||result.stdout);
for(const category of ['video_games','yugioh','one_piece'])assert.ok(fs.existsSync(path.join(out,category,'manifest.json')),category+' manifest missing');
for(const category of ['sports','comics'])assert.equal(fs.existsSync(path.join(out,category)),false,category+' is not available in this PriceCharting CSV subscription');
for(const excluded of ['pokemon','mtg'])assert.equal(fs.existsSync(path.join(out,excluded)),false,excluded+' must not use the shared PriceCharting pipeline');
const games=zlib.gunzipSync(fs.readFileSync(path.join(out,'video_games','test','products.jsonl.gz'))).toString().trim().split('\n').map(JSON.parse);
assert.equal(games[0].upc,'222222222222');
fs.rmSync(out,{recursive:true,force:true});
console.log('pricecharting offline contract tests passed');
