import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../dashboard.html',import.meta.url),'utf8');
assert.match(html,/WEBFLOW WEBSITE SYNC/);
assert.match(html,/IMPORT WEBFLOW → CLOUD/);
assert.match(html,/async function webflowMigrationPlan/);
assert.match(html,/wfId:i\.id,webflowId:i\.id/,'migration preserves Webflow IDs');
assert.match(html,/channelFlags:\{webflow:true,storefront:true,ebay:false\}/);
assert.match(html,/inventorySource:'built_in'/,'cloud becomes authoritative after migration');
assert.match(html,/Publish \/ Sync Webflow/);
assert.match(html,/Remove sold item from Webflow/,'cloud sales enqueue Webflow removal failures');
assert.match(html,/ebay_delist_needed/,'linked eBay sales leave a visible integration event');
assert.match(html,/width:72px; height:72px/,'inventory thumbnails are enlarged');
console.log('Webflow cloud sync contract passed');
