(function(root, factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  root.ArsCaDeckLab=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const SECTIONS={commander:'Commander',commanders:'Commander',deck:'Mainboard',main:'Mainboard',mainboard:'Mainboard',sideboard:'Sideboard',side:'Sideboard',maybeboard:'Maybeboard',maybe:'Maybeboard',considering:'Considering',tokens:'Tokens',token:'Tokens'};
  const CARD=/^(?:(SB|CMDR|COMMANDER)\s*:\s*)?(?:(\d+)\s*x?\s+(.+?)|(.+?)\s+x\s*(\d+))\s*$/i;
  function cleanName(raw){let value=String(raw||'').trim(),set='',collector='',m=value.match(/\s+\(([A-Z0-9]{2,8})\)\s+([A-Za-z0-9-]+)\s*$/i);if(m){set=m[1].toLowerCase();collector=m[2];value=value.slice(0,m.index).trim()}else{m=value.match(/\s+\[([A-Z0-9]{2,8})\]\s*$/i);if(m){set=m[1].toLowerCase();value=value.slice(0,m.index).trim()}const c=value.match(/\s+#([A-Za-z0-9-]+)\s*$/);if(c){collector=c[1];value=value.slice(0,c.index).trim()}}return{name:value.replace(/\s+\*F\*\s*$/i,'').trim(),set,collector}}
  function parseDecklist(input){const cards=[],ignored=[];let section='Mainboard',category='';String(input||'').replace(/^\uFEFF/,'').split(/\r?\n/).forEach((source,index)=>{const line=source.trim();if(!line||/^\/\//.test(line))return;if(/^(exported from|total\s*:?\s*\d+|name\s*,\s*quantity)/i.test(line)){ignored.push({line:index+1,text:line});return}const normalized=line.replace(/:$/,'').trim().toLowerCase();if(SECTIONS[normalized]){section=SECTIONS[normalized];category='';return}const inline=line.match(/^(Commander|Deck|Mainboard|Sideboard|Maybeboard|Considering|Tokens)\s*:\s*(.+)$/i),candidate=inline?inline[2].trim():line;if(inline)section=SECTIONS[inline[1].toLowerCase()]||section;const match=candidate.match(CARD);if(match){const prefix=(match[1]||'').toUpperCase(),quantity=Number(match[2]||match[5]||1),parsed=cleanName(match[3]||match[4]);if(prefix==='SB')section='Sideboard';if(prefix==='CMDR'||prefix==='COMMANDER')section='Commander';if(parsed.name&&quantity>0)cards.push({id:'dl_'+(index+1)+'_'+cards.length,quantity,name:parsed.name,set:parsed.set,collector:parsed.collector,section,category,sourceLine:index+1,status:'pending',card:null,error:''});return}if(!/[0-9]/.test(line)&&line.length<64){category=line.replace(/:$/,'').trim();return}ignored.push({line:index+1,text:line})});return{cards,ignored}}
  function normalizeName(value){return String(value||'').toLowerCase().normalize('NFKD').replace(/[’‘]/g,"'").replace(/[^a-z0-9/']+/g,' ').trim()}
  function canonicalType(typeLine){return['Land','Creature','Artifact','Enchantment','Planeswalker','Battle','Instant','Sorcery'].find(t=>new RegExp('\\b'+t+'\\b','i').test(String(typeLine||'')))||'Other'}
  function analyze(cards){const matched=cards.filter(x=>x.status==='matched'&&x.card&&['Commander','Mainboard'].includes(x.section)),counts={Commander:0,Mainboard:0,Sideboard:0,Maybeboard:0,Considering:0,Tokens:0},types={},curve={0:0,1:0,2:0,3:0,4:0,5:0,'6+':0};let lands=0,ramp=0,draw=0,removal=0,wipes=0,manaTotal=0,manaQty=0;cards.forEach(x=>counts[x.section]=(counts[x.section]||0)+Number(x.quantity||0));matched.forEach(entry=>{const q=Number(entry.quantity||1),card=entry.card,type=canonicalType(card.type_line);types[type]=(types[type]||0)+q;if(type==='Land')lands+=q;else{const mv=Number(card.cmc||0);curve[mv>=6?'6+':Math.max(0,Math.floor(mv))]+=q;manaTotal+=mv*q;manaQty+=q}const oracle=String(card.oracle_text||(card.card_faces||[]).map(f=>f.oracle_text||'').join(' ')).toLowerCase();if(/add (one mana|\{[wubrgc])|treasure token|search your library for (?:a|up to .*?) land|costs? (?:\{\d+\} )?less to cast/.test(oracle))ramp+=q;if(/draw (?:a|one|two|three|x|that many|cards equal)|investigate|exile the top .*you may (?:play|cast)/.test(oracle))draw+=q;if(/destroy target|exile target|counter target spell|deals? .* damage to target|target .* gets -\d+\/-\d+/.test(oracle))removal+=q;if(/destroy all|exile all|each creature gets -|deals? .* damage to each creature/.test(oracle))wipes+=q});return{total:cards.reduce((n,x)=>n+Number(x.quantity||0),0),matched:matched.reduce((n,x)=>n+Number(x.quantity||0),0),unmatched:cards.filter(x=>['unmatched','ambiguous','error'].includes(x.status)).reduce((n,x)=>n+Number(x.quantity||0),0),counts,types,curve,lands,ramp,draw,removal,wipes,averageManaValue:manaQty?manaTotal/manaQty:0}}
  function estimateBracket(cards,profile,metrics){const text=cards.filter(x=>x.card).map(x=>(x.card.name||'')+' '+(x.card.oracle_text||'')).join('\n').toLowerCase(),tutor=cards.filter(x=>x.card&&/search your library for (?:a|an) card/.test(String(x.card.oracle_text||'').toLowerCase())).reduce((n,x)=>n+x.quantity,0),fastMana=cards.filter(x=>x.card&&Number(x.card.cmc||0)<=1&&/add (?:two|three|\{[wubrgc]\}\{[wubrgc]\})/.test(String(x.card.oracle_text||'').toLowerCase())).reduce((n,x)=>n+x.quantity,0),extraTurns=(text.match(/take an extra turn/g)||[]).length;let bracket=2,goal=String(profile.power||'').toLowerCase();if(/upgraded|high power|bracket 4/.test(goal))bracket=3;if(/bracket 4|high power/.test(goal))bracket=4;if(/cedh|bracket 5/.test(goal))bracket=5;if(fastMana>=2||tutor>=4||extraTurns>=2)bracket=Math.max(bracket,4);if(metrics.total&&metrics.total<80&&String(profile.format).toLowerCase()==='commander')bracket=Math.min(bracket,3);const reasons=[profile.power?'Deck goal is '+profile.power+'.':'No power goal selected; estimate starts conservatively.',fastMana+' fast-mana signal'+(fastMana===1?'':'s')+' detected from verified card text.',tutor+' broad tutor signal'+(tutor===1?'':'s')+' detected from verified card text.',extraTurns+' extra-turn signal'+(extraTurns===1?'':'s')+' detected from verified card text.'];if(metrics.unmatched)reasons.push(metrics.unmatched+' unresolved card(s) excluded from the estimate.');return{bracket,label:['','Exhibition','Core','Upgraded','Optimized','cEDH'][bracket],reasons}}
  function matchInventory(cards,inventory){return cards.map(entry=>{const target=normalizeName(entry.card?.name||entry.name),matches=(inventory||[]).filter(item=>!['sold','archived'].includes(String(item.status||item.lifecycle||'').toLowerCase())&&/magic|mtg|tcg/i.test(String(item.category||item.itemType||''))&&normalizeName(item.name||item.title||item.cardName)===target&&Number(item.qty??item.quantity??1)>0),available=matches.reduce((n,item)=>n+Number(item.qty??item.quantity??1),0),selected=matches[0]||null,unitPrice=Number(selected?.salePrice??selected?.displayPrice??selected?.listPrice??selected?.market??selected?.marketPrice??0);return{...entry,inventoryMatches:matches,inventoryQty:available,selectedInventory:selected,availableValue:unitPrice*Math.min(entry.quantity,available)}})}
  function cleanedDecklist(cards,predicate){return['Commander','Mainboard','Sideboard','Maybeboard','Considering','Tokens'].map(section=>{const rows=cards.filter(x=>x.section===section&&(!predicate||predicate(x)));return rows.length?section+'\n'+rows.map(x=>x.quantity+' '+(x.card?.name||x.name)).join('\n'):''}).filter(Boolean).join('\n\n')}
  return{parseDecklist,cleanName,normalizeName,canonicalType,analyze,estimateBracket,matchInventory,cleanedDecklist};
});
