(function(root, factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  root.ArsCaDeckLab=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const SECTIONS={commander:'Commander',commanders:'Commander',deck:'Mainboard',main:'Mainboard',mainboard:'Mainboard',sideboard:'Sideboard',side:'Sideboard',maybeboard:'Maybeboard',maybe:'Maybeboard',considering:'Considering',tokens:'Tokens',token:'Tokens'};
  const HEADER_ALIASES={creatures:'Creatures',creature:'Creatures',artifacts:'Artifacts',artifact:'Artifacts',enchantments:'Enchantments',enchantment:'Enchantments',instants:'Instants',instant:'Instants',sorceries:'Sorceries',sorcery:'Sorceries',lands:'Lands',land:'Lands',planeswalkers:'Planeswalkers',planeswalker:'Planeswalkers',ramp:'Ramp',removal:'Removal',interaction:'Interaction',draw:'Draw',protection:'Protection'};
  function htmlDecode(value){return String(value||'').replace(/<br\s*\/?>/gi,'\n').replace(/<\/(?:div|p|li|tr)>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>')}
  function stripLineJunk(raw){return htmlDecode(raw).replace(/\t+/g,' ').replace(/\s+/g,' ').replace(/\s*(?:\/\/|#|--)\s*(?:price|usd|eur|tix|foil|nonfoil|owned|sideboard|maybe|comment).*$/i,'').replace(/\s+\$[\d,]+(?:\.\d{1,2})?(?:\s*(?:usd|eur))?\s*$/i,'').replace(/\s+(?:usd|eur|tix)\s*[\d,]+(?:\.\d{1,2})?\s*$/i,'').replace(/\s+\d+(?:\.\d{1,2})?\s*(?:tix)\s*$/i,'').replace(/\s+\*F\*\s*$/i,'').trim()}
  function cleanName(raw){let value=stripLineJunk(raw),set='',collector='';value=value.replace(/^\s*(?:SB|SIDEBOARD|CMDR|COMMANDER)\s*[:\-]\s*/i,'').replace(/^\s*(?:\d+\s*x?|x\s*\d+)\s+/i,'').replace(/\s+x\s*\d+\s*$/i,'').trim();let m=value.match(/\s+\(([A-Z0-9]{2,8})\)\s*([A-Za-z0-9-]+)?\s*$/i);if(m){set=m[1].toLowerCase();collector=m[2]||'';value=value.slice(0,m.index).trim()}else{m=value.match(/\s+\[([A-Z0-9]{2,8})\]\s*([A-Za-z0-9-]+)?\s*$/i);if(m){set=m[1].toLowerCase();collector=m[2]||'';value=value.slice(0,m.index).trim()}const c=value.match(/\s+#([A-Za-z0-9-]+)\s*$/);if(c){collector=c[1];value=value.slice(0,c.index).trim()}}value=value.replace(/\s+\{[^}]*\}\s*$/,'').replace(/\s+-\s+(?:foil|etched|borderless|showcase|extended art|promo)\s*$/i,'').replace(/\s+/g,' ').trim();return{name:value,set,collector,cleaned:value}}
  function parseQuantityAndName(candidate){const line=stripLineJunk(candidate);let m=line.match(/^(?:(SB|SIDEBOARD|CMDR|COMMANDER)\s*[:\-]\s*)?(?:(\d+)\s*x?\s+(.+)|x\s*(\d+)\s+(.+)|(.+?)\s+x\s*(\d+))$/i);if(!m)return null;const prefix=(m[1]||'').toUpperCase(),quantity=Number(m[2]||m[4]||m[7]||1),rawName=m[3]||m[5]||m[6]||'';if(!rawName||!quantity||quantity<1)return null;return{prefix,quantity,rawName}}
  function parseDecklist(input){const cards=[],ignored=[];let section='Mainboard',category='';htmlDecode(input).replace(/^\uFEFF/,'').split(/\r?\n/).forEach((source,index)=>{const rawLine=source,line=stripLineJunk(source);if(!line||/^\/\//.test(line))return;if(/^(exported from|total\s*:?\s*\d+|name\s*,\s*quantity|decklist|buy this deck|view as|download|copy|prices?|cards?\s+\d+)/i.test(line)){ignored.push({line:index+1,text:line,reason:'metadata'});return}const header=line.replace(/:$/,'').trim(),normalized=header.toLowerCase().replace(/\s*\(\d+\)\s*$/,'');if(SECTIONS[normalized]){section=SECTIONS[normalized];category='';return}if(HEADER_ALIASES[normalized]||(!/\d/.test(header)&&header.length<42&&/^[a-z][a-z\s/&-]+$/i.test(header))){category=HEADER_ALIASES[normalized]||header;return}const inline=line.match(/^(Commander|Deck|Mainboard|Sideboard|Maybeboard|Considering|Tokens)\s*[:\-]\s*(.+)$/i),candidate=inline?inline[2].trim():line;if(inline)section=SECTIONS[inline[1].toLowerCase()]||section;const match=parseQuantityAndName(candidate);if(match){const parsed=cleanName(match.rawName);if(match.prefix==='SB'||match.prefix==='SIDEBOARD')section='Sideboard';if(match.prefix==='CMDR'||match.prefix==='COMMANDER')section='Commander';if(parsed.name)cards.push({id:'dl_'+(index+1)+'_'+cards.length,quantity:match.quantity,name:parsed.name,cleanedName:parsed.cleaned,set:parsed.set,collector:parsed.collector,section,category,sourceLine:index+1,rawLine:rawLine.trim(),matchMethod:'pending',failureReason:'',status:'pending',card:null,error:''});return}ignored.push({line:index+1,text:line,reason:'unrecognized'})});return{cards,ignored}}
  function normalizeName(value){return String(value||'').toLowerCase().normalize('NFKD').replace(/[’‘]/g,"'").replace(/[^a-z0-9/']+/g,' ').trim()}
  function canonicalType(typeLine){return['Land','Creature','Artifact','Enchantment','Planeswalker','Battle','Instant','Sorcery'].find(t=>new RegExp('\\b'+t+'\\b','i').test(String(typeLine||'')))||'Other'}
  function analyze(cards){const matched=cards.filter(x=>x.status==='matched'&&x.card&&['Commander','Mainboard'].includes(x.section)),counts={Commander:0,Mainboard:0,Sideboard:0,Maybeboard:0,Considering:0,Tokens:0},types={},curve={0:0,1:0,2:0,3:0,4:0,5:0,'6+':0};let lands=0,ramp=0,draw=0,removal=0,wipes=0,manaTotal=0,manaQty=0;cards.forEach(x=>counts[x.section]=(counts[x.section]||0)+Number(x.quantity||0));matched.forEach(entry=>{const q=Number(entry.quantity||1),card=entry.card,type=canonicalType(card.type_line);types[type]=(types[type]||0)+q;if(type==='Land')lands+=q;else{const mv=Number(card.cmc||0);curve[mv>=6?'6+':Math.max(0,Math.floor(mv))]+=q;manaTotal+=mv*q;manaQty+=q}const oracle=String(card.oracle_text||(card.card_faces||[]).map(f=>f.oracle_text||'').join(' ')).toLowerCase();if(/add (one mana|\{[wubrgc])|treasure token|search your library for (?:a|up to .*?) land|costs? (?:\{\d+\} )?less to cast/.test(oracle))ramp+=q;if(/draw (?:a|one|two|three|x|that many|cards equal)|investigate|exile the top .*you may (?:play|cast)/.test(oracle))draw+=q;if(/destroy target|exile target|counter target spell|deals? .* damage to target|target .* gets -\d+\/-\d+/.test(oracle))removal+=q;if(/destroy all|exile all|each creature gets -|deals? .* damage to each creature/.test(oracle))wipes+=q});return{total:cards.reduce((n,x)=>n+Number(x.quantity||0),0),matched:matched.reduce((n,x)=>n+Number(x.quantity||0),0),unmatched:cards.filter(x=>['unmatched','ambiguous','error'].includes(x.status)).reduce((n,x)=>n+Number(x.quantity||0),0),counts,types,curve,lands,ramp,draw,removal,wipes,averageManaValue:manaQty?manaTotal/manaQty:0}}
  function estimateBracket(cards,profile,metrics){const text=cards.filter(x=>x.card).map(x=>(x.card.name||'')+' '+(x.card.oracle_text||'')).join('\n').toLowerCase(),tutor=cards.filter(x=>x.card&&/search your library for (?:a|an) card/.test(String(x.card.oracle_text||'').toLowerCase())).reduce((n,x)=>n+x.quantity,0),fastMana=cards.filter(x=>x.card&&Number(x.card.cmc||0)<=1&&/add (?:two|three|\{[wubrgc]\}\{[wubrgc]\})/.test(String(x.card.oracle_text||'').toLowerCase())).reduce((n,x)=>n+x.quantity,0),extraTurns=(text.match(/take an extra turn/g)||[]).length;let bracket=2,goal=String(profile.power||'').toLowerCase();if(/upgraded|high power|bracket 4/.test(goal))bracket=3;if(/bracket 4|high power/.test(goal))bracket=4;if(/cedh|bracket 5/.test(goal))bracket=5;if(fastMana>=2||tutor>=4||extraTurns>=2)bracket=Math.max(bracket,4);if(metrics.total&&metrics.total<80&&String(profile.format).toLowerCase()==='commander')bracket=Math.min(bracket,3);const reasons=[profile.power?'Deck goal is '+profile.power+'.':'No power goal selected; estimate starts conservatively.',fastMana+' fast-mana signal'+(fastMana===1?'':'s')+' detected from verified card text.',tutor+' broad tutor signal'+(tutor===1?'':'s')+' detected from verified card text.',extraTurns+' extra-turn signal'+(extraTurns===1?'':'s')+' detected from verified card text.'];if(metrics.unmatched)reasons.push(metrics.unmatched+' unresolved card(s) excluded from the estimate.');return{bracket,label:['','Exhibition','Core','Upgraded','Optimized','cEDH'][bracket],reasons}}
  function itemAvailableQty(item){const total=Number(item.quantity_available??item.qtyAvailable??item.availableQty??item.qty??item.quantity??item.quantity_total??1),reserved=Number(item.quantity_reserved??item.qtyReserved??item.reservedQty??0);return Math.max(0,total-reserved)}
  function itemPrice(item){return Number(item.salePrice??item.displayPrice??item.listPrice??item.price??item.market??item.marketPrice??0)}
  function itemFinish(item){return String(item.finish||item.foil||item.printing||'').toLowerCase().includes('foil')?'foil':'nonfoil'}
  function isSellableInventory(item){const status=String(item.status||item.lifecycle||'').toLowerCase();if(['sold','archived','deleted','draft','hold'].includes(status))return false;const flags=['online_sellable','vending_sellable','onlineSellable','vendingSellable','sellable'].filter(k=>Object.prototype.hasOwnProperty.call(item,k)&&item[k]!=null).map(k=>item[k]);if(flags.length&&!flags.some(value=>value===true||value===1||String(value).toLowerCase()==='true'))return false;return itemAvailableQty(item)>0}
  function matchInventory(cards,inventory){return cards.map(entry=>{const target=normalizeName(entry.card?.name||entry.name),requestedSet=String(entry.set||entry.card?.set||'').toLowerCase(),requestedCollector=String(entry.collector||entry.card?.collector_number||''),requestedFinish=String(entry.finish||'').toLowerCase(),allNameMatches=(inventory||[]).filter(item=>/magic|mtg|tcg|card/i.test(String(item.category||item.itemType||item.game||''))&&normalizeName(item.name||item.title||item.cardName)===target),sellable=allNameMatches.filter(isSellableInventory),exact=sellable.filter(item=>(!requestedSet||String(item.set||item.set_code||item.setCode||'').toLowerCase()===requestedSet)&&(!requestedCollector||String(item.collector||item.collector_number||item.collectorNumber||'')===requestedCollector)&&(!requestedFinish||itemFinish(item)===requestedFinish)),matches=(exact.length?exact:sellable).slice().sort((a,b)=>itemFinish(a).localeCompare(itemFinish(b))||itemPrice(a)-itemPrice(b)||String(a.condition||'').localeCompare(String(b.condition||''))),available=matches.reduce((n,item)=>n+itemAvailableQty(item),0),selected=matches[0]||null,selectedQty=Math.min(Number(entry.quantity||1),available),unitPrice=itemPrice(selected||{}),hasAny=allNameMatches.length>0,hasUnavailable=hasAny&&!sellable.length,exactRequested=!!(requestedSet||requestedCollector||requestedFinish),status=available>=Number(entry.quantity||1)?(exact.length||!exactRequested?'Exact Match':'Alternate Printing Available'):available>0?'Partial Fill':hasUnavailable?'Not Sellable':'Missing';return{...entry,inventoryMatches:matches,allInventoryMatches:allNameMatches,inventoryQty:available,selectedInventory:selected,fulfillmentStatus:entry.status==='matched'?status:'Needs Review',missingQty:entry.status==='matched'?Math.max(0,Number(entry.quantity||1)-available):Number(entry.quantity||1),walkoffQty:selectedQty,availableValue:unitPrice*selectedQty,selectedFinish:itemFinish(selected||{})}})}
  function cleanedDecklist(cards,predicate){return['Commander','Mainboard','Sideboard','Maybeboard','Considering','Tokens'].map(section=>{const rows=cards.filter(x=>x.section===section&&(!predicate||predicate(x)));return rows.length?section+'\n'+rows.map(x=>x.quantity+' '+(x.card?.name||x.name)).join('\n'):''}).filter(Boolean).join('\n\n')}
  return{parseDecklist,cleanName,normalizeName,canonicalType,analyze,estimateBracket,matchInventory,cleanedDecklist,itemAvailableQty,itemPrice,itemFinish,isSellableInventory};
});
